### ISSUE TITLE
Namespaces declared on child elements are lost in SVGReader::parseNode()

### ISSUE THREAD

**Issue by jarkko-hautakorpi** [meyfa/php-svg#62]
Seem that reading and appending `<svg><foreignObject>` to parent svg does not work, because namespaces are dropped from elements, which is why elements wont be visible in browsers?
So the example below can not be produced using php-svg (or simplexml?)
https://pastebin.com/21c73zAv
How can one preserve the namespaces in elements?

**Comment by meyfa** [comment]
I am happy to say this issue is finally resolved. Unfortunately, the solution requires PHP v5.4 or later, which is one minor version ahead of PHP-SVG's minimum. I did not find a method in SimpleXML that would provide namespace information on non-root elements for PHP 5.3. Either way, I will close the issue; if anyone has recommendations for what to do with 5.3 feel free to comment.
