### ISSUE TITLE
'toRasterImage()' takes forever

### ISSUE THREAD

**Issue by doublex** [meyfa/php-svg#86]
[forever.txt](https://github.com/meyfa/php-svg/files/5287062/forever.txt)

Testcase (file attached):

````php
$image = SVG::fromFile( "forever.txt" );
$doc = $image->getDocument();
$image = $image->toRasterImage( 160, 90 );
imagedestroy( $image );

````

**Comment by meyfa** [comment]
You are lucky it even gets this far. For me, PHP crashes with a memory exhaustion error. The issue seems to stem from huge Bezier curve coordinates in certain paths, for example:

```
<path d="M 0 0 C -637632.375 -78291 -1091067.875 -658662 -1012776.5 -1296294 C -942007.312 -1872663.25 -457000 -2308547.75 123627 -2317600 L 132695 -1736066.75 C -188476.375 -1731059.625 -444778.188 -1466639.625 -439771 -1145468 C -435245 -855155 -217302.687 -612651 70882 -577267 Z"
```

In reality, the coordinates have a completely different meaning due to preceding matrix transforms. In the example above:

```
matrix(0.0000787 0 0 -0.0000787 206.2943002 140.4940833)
```

Unfortunately, there is no transform support in PHP-SVG as of yet.
